# Generated by Django 4.2.1 on 2023-05-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/%y/%m/%d/', verbose_name='Rasm'),
        ),
    ]
