# Generated by Django 4.2.1 on 2023-05-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='PDF uchun sarlavha')),
                ('pdf_file', models.FileField(upload_to='pdf/%y/%m/%d/', verbose_name='Fayl')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.news', verbose_name='Qaysi yangilik uchun?')),
            ],
            options={
                'verbose_name': 'PDF Fayl',
                'verbose_name_plural': 'PDF Fayllar',
            },
        ),
    ]
