# Generated by Django 4.2.1 on 2023-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_pdfnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('businessman', models.CharField(max_length=255, verbose_name='Yuridik shaxs nomi(Tadbirkor)')),
                ('email', models.EmailField(max_length=255, verbose_name='Elektron manzil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('province_select', models.CharField(choices=[('Andijon viloyati', 'Andijon viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Buhoro viloyati', 'Buhoro viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Sirdaryo viloyat', 'Sirdaryo viloyat'), ('Farg`ona viloyati', 'Farg`ona viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Navoi viloyati', 'Navoi viloyati'), ('Qoraqalpog`iston viloyati', 'Qoraqalpog`iston viloyati')], max_length=255, verbose_name='Viloyat')),
                ('province', models.CharField(max_length=255, verbose_name='Viloyat')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('work_type', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yakka tartibdagi tadbirkor', 'Yakka tartibdagi tadbirkor'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=255, verbose_name='Shaxs')),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=255, verbose_name='Jinsi')),
                ('birthday', models.CharField(max_length=255, verbose_name='Tugilgan kun')),
                ('job', models.CharField(choices=[('Ish bilan taminlangan', 'Ish bilan taminlangan'), ('Ishsiz', 'Ishsiz'), ('Nafaqada', 'Nafaqada'), ('Talaba', 'Talaba')], max_length=255, verbose_name='Hozirgi kasb holati')),
                ('description', models.TextField(max_length=500, verbose_name='Murojaatnoma')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pdfnews',
            options={'verbose_name': 'PDF Fayl (Yangiliklar uchun)', 'verbose_name_plural': 'PDF Fayllar (Yangiliklar uchun)'},
        ),
    ]
