# Generated by Django 4.2.1 on 2023-05-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_people_name_alter_contact_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqalar'},
        ),
    ]
