# Generated by Django 4.2.1 on 2023-05-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Sarlavha')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='SubTag/%y/%m/%d/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('link', models.CharField(max_length=355, verbose_name='Havola')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tag')),
            ],
            options={
                'verbose_name': 'Qoshimcha Teg',
                'verbose_name_plural': 'Qoshimcha Teglar',
            },
        ),
    ]
