# Generated by Django 4.2.1 on 2023-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_subtag_title_ru_subtag_title_uz_tag_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, to='common.subcategory', verbose_name='Turkumi (shart emas)'),
        ),
    ]
